# Generated by Django 2.1.3 on 2018-11-11 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userco2',
            name='food_quantity',
            field=models.FloatField(blank=True, choices=[(0, 'Never'), (2.88, 'Almost never'), (5.76, 'Frequently'), (11.62, 'Very frequently')], default=0, verbose_name='Food quantity'),
        ),
        migrations.AlterField(
            model_name='userco2',
            name='housing_open',
            field=models.PositiveIntegerField(blank=True, verbose_name='House quantity open'),
        ),
        migrations.AlterField(
            model_name='userco2',
            name='housing_quantity_dict',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 'Freestanding NRW'), (3, 'Freestanding RW'), (5, 'Multistore aparment'), (7, 'Duplex row house'), (10, 'Luxury condominum')], default=1, verbose_name='Housing quantity option'),
        ),
    ]
