# Generated by Django 2.1.3 on 2018-11-11 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20181111_0745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userco2',
            name='housing_open',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='House quantity open'),
        ),
    ]
