# Generated by Django 2.1.3 on 2018-11-11 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20181111_0746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userco2',
            name='co2_owed',
            field=models.FloatField(blank=True, null=True, verbose_name='Owed CO2'),
        ),
        migrations.AlterField(
            model_name='userco2',
            name='co2_paid',
            field=models.FloatField(blank=True, null=True, verbose_name='Paid CO2'),
        ),
        migrations.AlterField(
            model_name='userco2',
            name='food_co2',
            field=models.FloatField(blank=True, null=True, verbose_name='Food CO2'),
        ),
        migrations.AlterField(
            model_name='userco2',
            name='fuel_economy_quantity',
            field=models.FloatField(blank=True, null=True, verbose_name='Fuel economy km/lts'),
        ),
        migrations.AlterField(
            model_name='userco2',
            name='housing_co2',
            field=models.FloatField(blank=True, null=True, verbose_name='Housing CO2'),
        ),
        migrations.AlterField(
            model_name='userco2',
            name='km_travel_quantity',
            field=models.FloatField(blank=True, null=True, verbose_name='Km travel'),
        ),
        migrations.AlterField(
            model_name='userco2',
            name='transportation_co2',
            field=models.FloatField(blank=True, null=True, verbose_name='Transportation CO2'),
        ),
    ]
