# Generated by Django 2.1.3 on 2018-11-11 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20181111_0747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertoken',
            name='tokens',
            field=models.DecimalField(decimal_places=10, default=50, max_digits=19, verbose_name='Tokens'),
        ),
    ]
