# Generated by Django 2.1.3 on 2018-11-11 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20181111_0855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertoken',
            name='tokens',
            field=models.DecimalField(decimal_places=10, default=10, max_digits=19, verbose_name='Tokens'),
        ),
    ]
