# Generated by Django 2.1.3 on 2018-11-11 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20181111_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userco2',
            name='co2_owed',
            field=models.FloatField(default=0, verbose_name='Owed CO2'),
        ),
        migrations.AlterField(
            model_name='userco2',
            name='co2_paid',
            field=models.FloatField(default=0, verbose_name='Paid CO2'),
        ),
    ]
