# Generated by Django 2.1.3 on 2018-11-11 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20181111_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertoken',
            name='tokens',
            field=models.FloatField(default=10, verbose_name='Tokens'),
        ),
    ]
