# Generated by Django 2.1.3 on 2018-11-11 06:21

from django.db import migrations, models
import django.db.models.deletion
import shortuuidfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FootPrint',
            fields=[
                ('uuid', shortuuidfield.fields.ShortUUIDField(blank=True, editable=False, max_length=22, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256, verbose_name='Name of FootPrint')),
                ('co2_multiplicative', models.PositiveIntegerField(default=10, verbose_name='CO2 Multiplicative')),
                ('transaction_type', models.CharField(choices=[('E', 'Egress'), ('I', 'Income')], default='E', max_length=1, verbose_name='Type of transaction')),
                ('fp_type', models.CharField(choices=[('I', 'Item'), ('D', 'Donation'), ('U', 'Action')], default='U', max_length=1, verbose_name='Type of footprint')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('uuid', shortuuidfield.fields.ShortUUIDField(blank=True, editable=False, max_length=22, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256, verbose_name="Item's name")),
                ('token_price', models.DecimalField(decimal_places=10, max_digits=19, verbose_name='Price in tokens')),
                ('picture', models.ImageField(upload_to='', verbose_name='Image')),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('uuid', shortuuidfield.fields.ShortUUIDField(blank=True, editable=False, max_length=22, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256, verbose_name="Organization's name")),
                ('eth_address', models.CharField(max_length=42, verbose_name='Core ETH address')),
                ('picture', models.ImageField(upload_to='', verbose_name='Image')),
            ],
        ),
        migrations.AddField(
            model_name='footprint',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='footprints.Item'),
        ),
        migrations.AddField(
            model_name='footprint',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='footprints.Organization'),
        ),
    ]
