# Generated by Django 2.1.3 on 2018-11-11 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footprints', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footprint',
            name='co2_multiplicative',
            field=models.FloatField(default=10, verbose_name='CO2 Multiplicative'),
        ),
    ]
