# Generated by Django 2.1.3 on 2018-11-11 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footprints', '0002_auto_20181111_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='token_price',
            field=models.FloatField(verbose_name='Price in tokens'),
        ),
    ]
